"""empty message

Revision ID: 09d9f1195c5a
Revises: 12cdb3792fee
Create Date: 2019-12-12 17:41:36.200525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d9f1195c5a'
down_revision = '12cdb3792fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('uom_id', sa.Integer(), nullable=False))
    op.drop_constraint('acc_id', 'accessories', type_='unique')
    op.create_unique_constraint('acc_id', 'accessories', ['name', 'desc', 'uom_id'])
    op.add_column('other_materials', sa.Column('uom_id', sa.Integer(), nullable=False))
    op.drop_constraint('oth_mat_id', 'other_materials', type_='unique')
    op.create_unique_constraint('oth_mat_id', 'other_materials', ['name', 'desc', 'uom_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oth_mat_id', 'other_materials', type_='unique')
    op.create_unique_constraint('oth_mat_id', 'other_materials', ['name', 'desc'])
    op.drop_column('other_materials', 'uom_id')
    op.drop_constraint('acc_id', 'accessories', type_='unique')
    op.create_unique_constraint('acc_id', 'accessories', ['name', 'desc'])
    op.drop_column('accessories', 'uom_id')
    # ### end Alembic commands ###
