"""empty message

Revision ID: 12cdb3792fee
Revises: bbec96969c49
Create Date: 2019-12-12 16:37:18.848162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12cdb3792fee'
down_revision = 'bbec96969c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_mat_uom')
    op.drop_table('accessories_mat_uom')
    op.drop_table('finished_mat_uom')
    op.drop_table('raw_mat_uom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_mat_uom',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('raw_mat_uom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['raw_item.id'], name='raw_mat_uom_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_mat_uom_id'], ['uom.id'], name='raw_mat_uom_ibfk_2', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('finished_mat_uom',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('finished_mat_uom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['finished_mat_uom_id'], ['uom.id'], name='finished_mat_uom_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['finished_item.id'], name='finished_mat_uom_ibfk_1', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accessories_mat_uom',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accessories_mat_uom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accessories_mat_uom_id'], ['uom.id'], name='accessories_mat_uom_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['accessories_item.id'], name='accessories_mat_uom_ibfk_1', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('other_mat_uom',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('other_mat_uom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['other_materials_item.id'], name='other_mat_uom_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['other_mat_uom_id'], ['uom.id'], name='other_mat_uom_ibfk_2', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
