"""empty message

Revision ID: 49dfb4ad9be4
Revises: cfeaca7a9de2
Create Date: 2019-11-25 17:56:05.865333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49dfb4ad9be4'
down_revision = 'cfeaca7a9de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_basic', 'finished_product_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_basic', sa.Column('finished_product_category', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
