"""empty message

Revision ID: bbec96969c49
Revises: 710b003cb4e7
Create Date: 2019-12-12 15:39:17.716010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbec96969c49'
down_revision = '710b003cb4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finished_goods', sa.Column('size_id', sa.Integer(), nullable=False))
    op.drop_constraint('finished_goods_id', 'finished_goods', type_='unique')
    op.create_unique_constraint('finished_goods_id', 'finished_goods', ['product_category_id', 'fabric_combination_id', 'print_technique_id', 'design_number_id', 'size_id', 'uom_id'])
    op.add_column('raw_goods', sa.Column('uom_id', sa.Integer(), nullable=False))
    op.drop_constraint('raw_goods_id', 'raw_goods', type_='unique')
    op.create_unique_constraint('raw_goods_id', 'raw_goods', ['yarn_id', 'fabric_process_id', 'fabric_width_id', 'fabric_dye_id', 'raw_material_category_id', 'fabric_construction_id', 'uom_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('raw_goods_id', 'raw_goods', type_='unique')
    op.create_unique_constraint('raw_goods_id', 'raw_goods', ['yarn_id', 'fabric_process_id', 'fabric_width_id', 'fabric_dye_id', 'raw_material_category_id', 'fabric_construction_id'])
    op.drop_column('raw_goods', 'uom_id')
    op.drop_constraint('finished_goods_id', 'finished_goods', type_='unique')
    op.create_unique_constraint('finished_goods_id', 'finished_goods', ['product_category_id', 'fabric_combination_id', 'print_technique_id', 'design_number_id'])
    op.drop_column('finished_goods', 'size_id')
    # ### end Alembic commands ###
