"""empty message

Revision ID: cfeaca7a9de2
Revises: 
Create Date: 2019-11-25 13:09:24.934766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfeaca7a9de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', 'finished_goods_code',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('transaction', 'image',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('transaction', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('transaction', 'report',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'report',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('transaction', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('transaction', 'image',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('transaction', 'finished_goods_code',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('transaction', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
